export const chocolateData = {
  division: {
    name: "VELOR",
    subtitle: "TERRA",
    tagline: "Grounded Indulgence",
    description: "Single-origin chocolate from Cameroonian cocoa grown in mineral-rich soil. Deeper flavor, richer fat content, unmistakable character. This is chocolate with substance.",
    collectionImage: "/images/velor-terra-collection.jpg",
    detailImage: "/images/velor-terra-detail.jpg",
    featureImage: "/images/velor-terra-judgment.jpg",
  },
  virtueCollection: [
    {
      id: "judgment",
      name: "JUDGMENT",
      type: "Milk Chocolate",
      cocoa: "45%",
      tagline: "Control the impulse, taste the decision.",
      description: "Premium milk chocolate that rewards restraint. Creamy, rich, and satisfying — but never excessive.",
    },
    {
      id: "resolve",
      name: "RESOLVE",
      type: "Milk Chocolate",
      cocoa: "50%",
      tagline: "Stay ready. Stay sharp.",
      description: "A bolder milk chocolate for those who prefer substance. Higher cocoa content, deeper flavor, unwavering quality.",
    },
    {
      id: "restraint",
      name: "RESTRAINT",
      type: "Dark Chocolate",
      cocoa: "70%",
      tagline: "Strength in moderation.",
      description: "Dark chocolate that proves less is more. Intense cocoa notes, subtle bitterness, profound satisfaction.",
    },
    {
      id: "focus",
      name: "FOCUS",
      type: "Dark Chocolate",
      cocoa: "75%",
      tagline: "Master your mind.",
      description: "For the purist. High cocoa content delivers clarity of flavor — no distractions, just depth.",
    },
    {
      id: "order",
      name: "ORDER",
      type: "Dark Chocolate",
      cocoa: "80%",
      tagline: "Prioritize perfection.",
      description: "Our darkest expression. Minimal sugar, maximum character. Chocolate reduced to its essential truth.",
    },
  ],
  categories: {
    dark: {
      title: "Origin Dark Collection",
      subtitle: "The Core Range",
      description: "70% / 75% / 80% single-origin bars. This is the signature Velor Terra flavor profile — awards-worthy, credibility-building, unmistakably premium.",
      products: ["restraint", "focus", "order"],
    },
    milk: {
      title: "Origin Milk Collection",
      subtitle: "Creamy, Yet Premium",
      description: "45-55% cocoa — significantly higher than commercial brands. The creaminess you expect, the quality you deserve.",
      products: ["judgment", "resolve"],
    },
    infused: {
      title: "Infused Collection",
      subtitle: "The Unique Lane",
      description: "Where tradition meets innovation. Our cocoa paired with complementary ingredients that elevate without overwhelming.",
      variants: [
        { name: "Cocoa + Coffee", note: "Connects to VELOR CAF" },
        { name: "Cocoa + African Spices", note: "Warm, aromatic" },
        { name: "Cocoa + Sea Salt", note: "Sweet meets mineral" },
        { name: "Cocoa + Roasted Nibs", note: "Texture and depth" },
        { name: "Cocoa + Chilli", note: "Heat with sophistication" },
      ],
    },
  },
  specs: {
    weight: "100g",
    origin: "Cameroon",
    certification: "Single Origin",
  },
  story: {
    title: "The Terroir Story",
    highlight: "You can taste the earth in every bite.",
    paragraphs: [
      "Our cocoa grows in mineral-rich soil that creates an unmistakable flavor profile. Deeper notes, richer fat content, a character that cannot be replicated elsewhere.",
      "Fermentation happens in wooden boxes built by the same hands that harvest the pods. Sun-dried under real African sunlight — not industrial heat lamps.",
      "The result is chocolate with terroir. Like great wine, our bars express where they come from. This isn't commodity cocoa. This is Velor Terra.",
    ],
  },
  craftProcess: [
    { step: 1, title: "Traditional Fermentation", description: "Wooden boxes, ancestral methods, 5-7 days of transformation" },
    { step: 2, title: "Sun Drying", description: "Real sunlight, daily turning, natural preservation" },
    { step: 3, title: "Small-Batch Grinding", description: "Stone ground to preserve oils and develop flavor" },
    { step: 4, title: "Slow Conching", description: "72+ hours of refining for ultimate smoothness" },
  ],
};
